spring.application.name=ucoshopapi
spring.datasource.url=jdbc:postgresql://localhost:5432/ucoshopadmindb
spring.datasource.username=postgres
spring.datasource.password=0000
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_cregation=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=8081


# Agrega estas líneas desde el client.properties del API
client.frequentlyquestion.process.routingkey-name-save=ucoshopapi.frequentlyquestion.process.client.rk
client.frequentlyquestion.process.exchange-name-save=ucoshopapi.frequentlyquestion.process.client.ex
client.frequentlyquestion.process.queue-name-save=ucoshopapi.frequentlyquestion.process.client.qu

client.answer.process.routingkey-name-save=ucoshopapi.answer.process.client.rk
client.answer.process.exchange-name-save=ucoshopapi.answer.process.client.ex
client.answer.process.queue-name-save=ucoshopapi.answer.process.client.qu

