spring.application.name=ucoshopapi
spring.datasource.url=jdbc:postgresql://localhost:5433/ucoshopadmindb
spring.datasource.username=postgres
spring.datasource.password=123
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_cregation=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
server.port=8081
spring.rabbitmq.virtual-host=/
rabbitmq.dynamic=false

# Colas y exchanges RabbitMQ para payment
client.payment.process.routingkey-name-patch=ucoshopapi.payment.process.client.rk
client.payment.process.exchange-name-patch=ucoshopapi.payment.process.client.ex
client.payment.process.queue-name-patch=ucoshopapi.payment.process.client.qu


# Agrega estas líneas desde el client.properties del API
client.frequentlyquestion.process.routingkey-name-save=ucoshopapi.frequentlyquestion.process.client.rk
client.frequentlyquestion.process.exchange-name-save=ucoshopapi.frequentlyquestion.process.client.ex
client.frequentlyquestion.process.queue-name-save=ucoshopapi.frequentlyquestion.process.client.qu

client.answer.process.routingkey-name-save=ucoshopapi.answer.process.client.rk
client.answer.process.exchange-name-save=ucoshopapi.answer.process.client.ex
client.answer.process.queue-name-save=ucoshopapi.answer.process.client.qu

client.question.process.routingkey-name-save=ucoshopapi.question.process.client.rk
client.question.process.exchange-name-save=ucoshopapi.question.process.client.ex
client.question.process.queue-name-save=ucoshopapi.question.process.client.qu